#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/prerm.d && run-parts --arg="5.15.67test-project0-kernel1+" --arg="/boot/vmlinuz-5.15.67test-project0-kernel1+" /etc/kernel/prerm.d
exit 0
